### ISSUE TITLE
Upload of stemcell fails with AWS us-west-1

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-community/bosh-bootstrap#204]
Version 0.11.4

Uploading stemcell                  |oo                      | 1/11 00:00:01  ETA: 00:00:09create stemcell failed: 
No route to host - connect(2) (http://169.254.169.254:80):
/usr/local/var/rbenv/versions/1.9.3-p392/gemsets/bosh-bootstrap/gems/httpclient-2.2.4/lib/httpclient/session.rb:775
:in `initialize'

Does that IP need to be a DNS name?

**Comment by aetelani** [comment]
i am having same error message with eu-west-1, is there a trick to get it working?
