### ISSUE TITLE
bosh-bootstrap 0.11.4 results in error

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community/bosh-bootstrap#207]
just upgraded to 0.11.4 and get the error below
i also tried to clean all gems and reinstall again but same problem occurs

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/bosh-bootstrap-0.11.4/bin/bosh-bootstrap:5:in `<top (required)>'
    from /usr/local/bin/bosh-bootstrap:23:in `load'
    from /usr/local/bin/bosh-bootstrap:23:in `<main>'
```

**Comment by lanzalibre** [comment]
I am having the same problem again. Can you provide some help?

**Comment by lanzalibre** [comment]
Fixed it with sudo gem install bundler

**Comment by drnic** [comment]
Perhaps we need to install bundler as part of the gem install. Lots of people already have it so I forgot some don't.

**Comment by lanzalibre** [comment]
Maybe I am too much of a newbie, but I wonder if you could help me with the fourth step. It says it does not recognize "cf" as a command. This image shows the current status of my installation.

![screen shot 2015-09-12 at 07 49 31](https://cloud.githubusercontent.com/assets/7738670/9830142/203d96c6-5923-11e5-9d3b-c987e7dd530f.png)

**Comment by drnic** [comment]
I think you're now trying to use the old bosh-cloudfoundry project. It's unmaintained and looks like it no longer works - I'm sorry.

Now look to the CF & bosh.io docs to learn more about deploying CF

**Comment by lanzalibre** [comment]
I had never worked with bosh or cf before this. All I did was install bosh
as per the instructions (same as in bosh.io):

gem install bosh_cli

By the way, my version of bosh says

bosh -v

BOSH 1.3069.0

2015-09-12 8:11 GMT+02:00 Dr Nic Williams <notifications@github.com>:

**Comment by jason-o** [comment]
Attempting to run :
 ./scripts/generate-bosh-lite-dev-manifest

I was getting the following:
"_**vagrant@bosh-lite:~/workspace/cf-release$ ./scripts/generate-bosh-lite-dev-manifest
/usr/local/lib/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)

        from /usr/local/lib/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)

        from /usr/local/lib/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Can only target Bosh Lite Director. Please use 'bosh target' before running this script.**_"

Running:
sudo apt-get install bundler ruby-bundler
resolved this for me.

I've seen posts in the past, where this might have been resolved, however this post is of course 03/18/2016
My occurrence was on a new / clean pc, following the CF instructions. 
Downloaded the latest of everything that was suggested. Using vagrant 1.8, cf project / stem cell 232, etc on a new pc.
