### ISSUE TITLE
Failure "Uploading stemcell"

### ISSUE THREAD

**Issue by mdub** [cloudfoundry-community/bosh-bootstrap#216]
Running "bundle exec bin/bosh-bootstrap deploy" from source (SHA1 ac8fa55), and choosing AWS in ap-southeast-2, I get:

```
...
Stemcell info
-------------
Name:    micro-bosh-stemcell
Version: 699


Deploy Micro BOSH
  unpacking stemcell (00:00:06)                                                             
Uploading stemcell               |oo                    | 1/11 00:00:13  ETA: 00:01:02create stemcell failed: Timed out reading instance metadata, please make sure CPI is running on EC2 instance:
/Users/mdub/.gem/ruby/1.9.3/gems/bosh_aws_cpi-1.5.0.pre.699/lib/cloud/aws/helpers.rb:14:in `cloud_error'
```

**Comment by sranasinghe** [comment]
vagrant@vagrant-ubuntu-trusty:~/micro-deployment$ bosh micro deploy bosh-stemcell-3197-aws-xen-ubuntu-trusty-go_agent.tgz

No `bosh-deployments.yml` file found in current directory.

Conventionally, `bosh-deployments.yml` should be saved in /home/vagrant.
Is /home/vagrant/micro-deployment a directory where you can save state? (type 'yes' to continue): yes
Deploying new micro BOSH instance `manifest.yml' to `https://52.25.49.76:25555' (type 'yes' to continue): yes

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-aws-xen-ubuntu-trusty-go_agent
Version: 3197

  Started deploy micro bosh
  Started deploy micro bosh > Unpacking stemcell. Done (00:00:05)
  Started deploy micro bosh > Uploading stemcelllog writing failed. can't be called from trap context
create stemcell failed: Timed out reading instance metadata, please make sure CPI is running on EC2 instance:
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_aws_cpi-2.1.1/lib/cloud/aws/helpers.rb:32:in `cloud_error'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_aws_cpi-2.1.1/lib/cloud/aws/cloud.rb:97:in `rescue in current_vm_id'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_aws_cpi-2.1.1/lib/cloud/aws/cloud.rb:78:in `current_vm_id'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_aws_cpi-2.1.1/lib/cloud/aws/cloud.rb:465:in `block in create_stemcell'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_common-1.3202.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_aws_cpi-2.1.1/lib/cloud/aws/cloud.rb:453:in `create_stemcell'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cpi-1.3202.0/lib/cloud/internal_cpi.rb:22:in `invoke_cpi_method'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cpi-1.3202.0/lib/cloud/internal_cpi.rb:10:in `method_missing'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:228:in `block (2 levels) in create_stemcell'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:85:in `step'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:227:in `block in create_stemcell'
/home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:213:in `create_stemcell'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:118:in `create'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:98:in `block in create_deployment'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:92:in `with_lifecycle'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/deployer/instance_manager.rb:98:in `create_deployment'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli_plugin_micro-1.3202.0/lib/bosh/cli/commands/micro.rb:179:in `perform'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli-1.3202.0/lib/cli/command_handler.rb:57:in `run'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli-1.3202.0/lib/cli/runner.rb:59:in `run'
/home/vagrant/.rvm/gems/ruby-2.2.1/gems/bosh_cli-1.3202.0/bin/bosh:19:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.2.1/bin/bosh:23:in `load'
/home/vagrant/.rvm/gems/ruby-2.2.1/bin/bosh:23:in `<main>'
/home/vagrant/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
vagrant@vagrant-ubuntu-trusty:~/micro-deployment$

**Comment by sranasinghe** [comment]
Sorry just posted with out asking the question .... do you or anyone happen to know whats going on here .. I m running my bosh commands from my vagrant box running on my computer  ... any suggestions are greatly appreciated as i trying to figure out what did i do wrong for few days now .... Thank you ... also please let me know if you need any other info
