### ISSUE TITLE
Unable to compile - Timeout

### ISSUE THREAD

**Issue by celek** [cloudfoundry-community/bosh-bootstrap#274]
*\* newbie **
running ceploy of cf 177 following : http://docs.cloudfoundry.org/deploying/ec2/deploy_aws_cf.html

getting stuck here:  Started compiling packages > buildpack_cache/4ced0bc62f12dcaa79121718ca3525253ede33b5[WARNING] cannot access director, trying 4 more times...

I opened all port on bosh for my cf security group and vice versa otherwise I was getting time out..

I can't connect to the BOSH vm using SSH to debug, I am getting
ssh -i /home/cfamin/.ssh/BOSH admin@x.y.z
Permission denied (publickey).
for admin, ec2-user and ubuntu - I do have the private key in my local system

**Comment by gogularaja** [comment]
@drnic 

After giving "bosh deploy" , i have been facing this issue

 Started compiling packages
  Started compiling packages > rootfs_cflinuxfs2/85e207d5f9485efb23128b5e0affb79dc168c260
  Started compiling packages > cli/2b0725c955992dec52458aeb9e764d9f4be18d0a
  Started compiling packages > buildpack_java_offline/8d50a6f07c5b40a4f6fb33fcfb31141b75e1e32b
  Started compiling packages > buildpack_java/7bf19e9264b1a03d7bf1320e5e4504e946fbae59
  Started compiling packages > nginx/bf3af6163e13887aacd230bbbc5eff90213ac6af
  Started compiling packages > ruby-2.2.4/dd1b827e6ea0ca7e9fcb95d08ae81fb82f035261
   Failed compiling packages > buildpack_java_offline/8d50a6f07c5b40a4f6fb33fcfb31141b75e1e32b: Timed out pinging to 58f2f9f3-b296-493e-9b25-80e61feb8a41 after 600 seconds (00:10:56)
   Failed compiling packages > ruby-2.2.4/dd1b827e6ea0ca7e9fcb95d08ae81fb82f035261: Timed out pinging to fd563468-2796-492a-a98d-123c6173f91c after 600 seconds (00:11:02)
   Failed compiling packages > buildpack_java/7bf19e9264b1a03d7bf1320e5e4504e946fbae59: Timed out pinging to 169e339e-d0ee-4531-8aa8-99bf5a58bd95 after 600 seconds (00:11:11)
   Failed compiling packages > cli/2b0725c955992dec52458aeb9e764d9f4be18d0a: Timed out pinging to 85e81b11-f289-4adb-b1a8-19a978dd6cc5 after 600 seconds (00:11:12)
   Failed compiling packages > nginx/bf3af6163e13887aacd230bbbc5eff90213ac6af: Timed out pinging to a4ab58da-7a82-4c70-b777-0f2bc4110018 after 600 seconds (00:11:13)
   Failed compiling packages > rootfs_cflinuxfs2/85e207d5f9485efb23128b5e0affb79dc168c260: Timed out pinging to aa3f0546-d777-4540-8c69-962fe18f39f8 after 600 seconds (00:11:14)

Error 450002: Timed out pinging to 58f2f9f3-b296-493e-9b25-80e61feb8a41 after 600 seconds
