### ISSUE TITLE
bosh-bootstrap deploy is failed with the Runtime Error.

### ISSUE THREAD

**Issue by harikrishna1210** [cloudfoundry-community/bosh-bootstrap#311]
bosh-bootstrap deploy is failed with the  Runtime Error.
Could you please check and advise where we went wrong.
ERROR:
=======
[root@ip-172-31-18-217 ~]# bosh-bootstrap deploy

Confirming: Using AWS EC2/ap-southeast-1

Confirming: Using address 172.31.0.4
Reusing security group ssh-vpc-5bc63d3e for the VPC
 -> no additional ports opened
Reusing security group dns-server-vpc-5bc63d3e for the VPC
 -> no additional ports opened
Reusing security group bosh-vpc-5bc63d3e for the VPC
 -> no additional ports opened

Confirming: Using key pair firstbosh
Determining stemcell image/file to use... /root/deployments/firstbosh/bosh-stemcell-2950-aws-xen-ubuntu-trusty-go_agent.tgz
bosh micro deployment firstbosh
Deployment set to '/root/deployments/firstbosh/micro_bosh.yml'
bosh -n micro deploy --update-if-exists /root/deployments/firstbosh/bosh-stemcell-2950-aws-xen-ubuntu-trusty-go_agent.tgz

Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-aws-xen-ubuntu-trusty-go_agent
Version: 2950

/usr/local/share/gems/gems/fog-aws-0.1.2/lib/fog/aws/auto_scaling.rb:4:in `<class:AutoScaling>': uninitialized constant Fog::AWS::CredentialFetcher (NameError)
        from /usr/local/share/gems/gems/fog-aws-0.1.2/lib/fog/aws/auto_scaling.rb:3:in `<module:AWS>'
        from /usr/local/share/gems/gems/fog-aws-0.1.2/lib/fog/aws/auto_scaling.rb:2:in `<module:Fog>'
        from /usr/local/share/gems/gems/fog-aws-0.1.2/lib/fog/aws/auto_scaling.rb:1:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `require'
        from /usr/local/share/gems/gems/fog-1.27.0/lib/fog/aws.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/local/share/gems/gems/fog-1.27.0/lib/fog.rb:23:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/local/share/gems/gems/bosh-registry-1.2950.0/lib/bosh/registry.rb:10:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/local/share/gems/gems/bosh-registry-1.2950.0/bin/bosh-registry:3:in `<top (required)>'
        from /usr/local/bin/bosh-registry:23:in `load'
        from /usr/local/bin/bosh-registry:23:in `<main>'
`bosh-registry -c /tmp/d20150430-29774-utqvxj/bosh_registry_yml20150430-29774-ift82q` failed, exit status=1
/usr/local/share/gems/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (1): [bosh -n micro deploy --update-if-

exists /r...] (RuntimeError)
        from /usr/local/share/gems/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
        from /usr/local/share/gems/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/cli/helpers/bundle.rb:18:in `block in run'
        from /usr/local/share/gems/gems/bundler-1.9.5/lib/bundler.rb:247:in `block in with_clean_env'
        from /usr/local/share/gems/gems/bundler-1.9.5/lib/bundler.rb:234:in `with_original_env'
        from /usr/local/share/gems/gems/bundler-1.9.5/lib/bundler.rb:240:in `with_clean_env'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/cli/helpers/bundle.rb:16:in `run'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/microbosh.rb:54:in `block in deploy_or_update'
        from /usr/share/ruby/fileutils.rb:125:in `chdir'
        from /usr/share/ruby/fileutils.rb:125:in `cd'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/microbosh.rb:52:in `deploy_or_update'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/microbosh.rb:42:in `block in deploy'
        from /usr/share/ruby/fileutils.rb:125:in `chdir'
        from /usr/share/ruby/fileutils.rb:125:in `cd'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/microbosh.rb:40:in `deploy'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/cli/commands/deploy.rb:77:in `perform_microbosh_deploy'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/cli/commands/deploy.rb:24:in `perform'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/lib/bosh-bootstrap/thor_cli.rb:11:in `deploy'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/share/gems/gems/bosh-bootstrap-0.17.0/bin/bosh-bootstrap:13:in `<top (required)>'
        from /usr/local/bin/bosh-bootstrap:23:in `load'
        from /usr/local/bin/bosh-bootstrap:23:in `<main>'
[root@ip-172-31-18-217 ~]#

Setup:
=====
[root@ip-172-31-18-217 ~]# ruby -v
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
[root@ip-172-31-18-217 ~]# bosh -v
BOSH 1.2950.0
[root@ip-172-31-18-217 ~]#
gem list | grep bosh-bootstrap
bosh-bootstrap (0.17.0)
[root@ip-172-31-18-217 ~]#

**Comment by drnic** [comment]
Annoying fog issue.




My work around is to create a Gemfile with bosh-bootstrap and fog-aws (restricted to v 0.1.1)




Or delete fog-aws 0.1.2 and install 0.1.1

**Comment by harikrishna1210** [comment]
Un installed the fog-aws 0.1.2 and installed the fog-aws 0.1.1
Issue is resolved.
Thank you very much.

**Comment by drnic** [comment]
@cppforlife anyone raised this bug already for microbosh? It's been around a few weeks at least. I keep forgetting to create a bug report.
