### ISSUE TITLE
Question about using bosh-init as deployment tool.

### ISSUE THREAD

**Issue by allomov** [cloudfoundry-community/bosh-bootstrap#318]
Hey, all.

I am very interested in knowing your plans on future of this project. Particularly if you plan to switch to using `bosh-init` as a main deployment tool?

Thank you.

**Comment by drnic** [comment]
My main goal that drove me to write bosh-bootstrap and keep supporting it is to make it super easy to get started with bosh.




Figuring out how to construct a micro-bosh.yml wasn't ever trivial; and you didn't learn anything about using bosh from the activity (diff schema from a bosh manifest)




With bosh-init we now have a schema that is closer to what a normal bosh manifest looks like - so on one side, automatically generating it for someone seems to take away from the learning process.




But on the other side, a bosh-init manifest is longer and currently more complicated than micro-bosh.yml so I can imagine as a user I would want a way to simplify how to get started.




In production we're now generating micro-bosh.yml using spiff and/or spruce and deploying via concourse.ci pipelines. In future it would generate bosh-init manifests.




So it's possible that nextgen of bosh-bootstrap is a different type of tool; with a different short and long term goal for a user.




But the future is bosh-init

**Comment by allomov** [comment]
Thank you for the answer. I was wondering because I wanted to update `terraform-openstack-cf-install`, which uses `bosh-bootstrap` by adding the latest cf and possibility to set AZ. Still using `bosh-init` here seems more natural for me and I will switch to using it.

**Comment by drnic** [comment]
If started spiking out bosh-init support in terraform-aws-bosh repo at the start of the year. Perhaps have a look there too. It's not as supported as terraform-aws-cf-install (it's my play area)
